typedef unsigned int u32;
typedef signed int s32;
typedef unsigned char u8;
typedef signed char s8;
extern void delay_ms(unsigned int ms);
extern void delay_sec(unsigned int sec);
extern void lcd_data(unsigned char data);
extern void lcd_cmd(unsigned char cmd);
extern void lcd_init(void);
extern void lcd_string(char *ptr);
extern void uart0_init(u32 baud);
extern void uart0_tx(u8 data);
extern void uart0_tx_string(s8 *ptr);
extern u8 uart0_rx(void);
extern void uart0_handler(void)__irq;
extern void config_vic(void);
extern void uart0_interrupt(void);
extern void i2c_init(void);
extern void i2c_byte_write_frame(u8 sa,u8 mr,u8 data);
extern u8 i2c_byte_read_frame(u8 sa,u8 mr);
